// apps/vue/app/app.vue
<template>
  <main
    class="bg-newt-bg-base text-newt-text-primary flex min-h-screen flex-col items-center justify-center gap-4 px-6 text-center"
  >
    <h1 class="font-display text-3xl font-bold">newt/ui</h1>
    <p class="text-newt-text-secondary max-w-prose text-sm">
      This deployment serves the Vue component registry under
      <code class="font-mono">/r</code>. Documentation lives on the main site.
    </p>
    <a
      class="text-newt-text-link text-sm underline-offset-4 hover:underline"
      href="https://github.com/wolfstar-project/newt-ui"
    >
      github.com/wolfstar-project/newt-ui
    </a>
  </main>
</template>

// apps/www/app/page.tsx
const DOCS_URL = "https://github.com/wolfstar-project/newt-ui"

export default function HomePage() {
  return (
    <main className="mx-auto flex min-h-screen max-w-2xl flex-col justify-center gap-4 bg-newt-bg-base px-6 py-16">
      <h1 className="text-3xl font-bold text-newt-text-primary">newt/ui</h1>
      <p className="text-newt-text-secondary">
        This deployment only serves the React component registry under{" "}
        <code className="text-newt-text-primary">/r</code>, consumed by the{" "}
        <code className="text-newt-text-primary">@wolfstar/newt-ui</code> CLI.
      </p>
      <a
        className="text-newt-text-link underline underline-offset-4"
        href={DOCS_URL}
      >
        Read the documentation
      </a>
    </main>
  )
}
