// apps/www/registry/default/example/action-row-demo.tsx
import { ActionRow } from "@/registry/default/ui/action-row"
import { Button } from "@/registry/default/ui/button"

export default function ActionRowDemo() {
  return (
    <ActionRow aria-label="Message actions">
      <Button variant="primary">Accept</Button>
      <Button variant="secondary">Decline</Button>
    </ActionRow>
  )
}

// apps/vue/app/lib/registry/default/example/ActionRowDemo.vue
<script setup lang="ts">
import { ActionRow } from "@/lib/registry/default/ui/action-row"
import { Button } from "@/lib/registry/default/ui/button"
</script>

<template>
  <ActionRow aria-label="Message actions">
    <Button variant="primary">Accept</Button>
    <Button variant="secondary">Decline</Button>
  </ActionRow>
</template>
