// apps/www/registry/default/example/badge-demo.tsx
import { Badge } from "@/registry/default/ui/badge"

export default function BadgeDemo() {
  return (
    <div className="flex flex-wrap items-center gap-2">
      <Badge variant="brand" dot>
        Brand
      </Badge>
      <Badge variant="success" dot>
        Online
      </Badge>
      <Badge variant="danger" dot>
        Error
      </Badge>
    </div>
  )
}

// apps/vue/app/lib/registry/default/example/BadgeDemo.vue
<script setup lang="ts">
import { Badge } from "@/lib/registry/default/ui/badge"
</script>

<template>
  <div class="flex flex-wrap items-center gap-2">
    <Badge variant="brand" dot>Brand</Badge>
    <Badge variant="success" dot>Online</Badge>
    <Badge variant="danger" dot>Error</Badge>
  </div>
</template>
