// apps/www/registry/default/example/message-composer-demo.tsx
"use client"

import * as React from "react"

import { MessageComposer } from "@/registry/default/ui/message-composer"

export default function MessageComposerDemo() {
  const [value, setValue] = React.useState("")

  return (
    <MessageComposer
      channelName="general"
      value={value}
      onValueChange={setValue}
      onSubmit={() => setValue("")}
      className="w-full max-w-md"
    />
  )
}

// apps/vue/app/lib/registry/default/example/MessageComposerDemo.vue
<script setup lang="ts">
import { ref } from "vue"

import { MessageComposer } from "@/lib/registry/default/ui/message-composer"

const value = ref("")
</script>

<template>
  <MessageComposer
    v-model="value"
    channel-name="general"
    class="w-full max-w-md"
    @submit="value = ''"
  />
</template>
