// apps/www/registry/default/example/select-menu-demo.tsx
"use client"

import * as React from "react"

import {
  SelectMenu,
  SelectMenuLabel,
  SelectMenuOption,
  SelectMenuSearch,
} from "@/registry/default/ui/select-menu"

const options = ["Option one", "Option two", "Option three"]

export default function SelectMenuDemo() {
  const [selected, setSelected] = React.useState(options[0])
  const [query, setQuery] = React.useState("")

  const visible = options.filter((option) =>
    option.toLowerCase().includes(query.trim().toLowerCase())
  )

  return (
    <SelectMenu aria-label="Select an option">
      <SelectMenuSearch
        placeholder="Search…"
        aria-label="Search options"
        value={query}
        onChange={(event) => setQuery(event.target.value)}
      />
      <SelectMenuLabel>Options</SelectMenuLabel>
      {visible.map((option) => (
        <SelectMenuOption
          key={option}
          selected={option === selected}
          onClick={() => setSelected(option)}
        >
          {option}
        </SelectMenuOption>
      ))}
    </SelectMenu>
  )
}

// apps/vue/app/lib/registry/default/example/SelectMenuDemo.vue
<script setup lang="ts">
import { computed, ref } from "vue"

import {
  SelectMenu,
  SelectMenuLabel,
  SelectMenuOption,
  SelectMenuSearch,
} from "@/lib/registry/default/ui/select-menu"

const options = ["Option one", "Option two", "Option three"]
const selected = ref(options[0])
const query = ref("")

const visible = computed(() =>
  options.filter((option) =>
    option.toLowerCase().includes(query.value.trim().toLowerCase())
  )
)
</script>

<template>
  <SelectMenu aria-label="Select an option">
    <SelectMenuSearch
      v-model="query"
      placeholder="Search…"
      aria-label="Search options"
    />
    <SelectMenuLabel>Options</SelectMenuLabel>
    <SelectMenuOption
      v-for="option in visible"
      :key="option"
      :selected="option === selected"
      @click="selected = option"
    >
      {{ option }}
    </SelectMenuOption>
  </SelectMenu>
</template>
