// apps/www/registry/default/example/tabs-demo.tsx
import { Tabs, TabsTrigger } from "@/registry/default/ui/tabs"

export default function TabsDemo() {
  return (
    <Tabs defaultValue="one">
      <TabsTrigger value="one">Tab one</TabsTrigger>
      <TabsTrigger value="two">Tab two</TabsTrigger>
      <TabsTrigger value="three">Tab three</TabsTrigger>
    </Tabs>
  )
}

// apps/vue/app/lib/registry/default/example/TabsDemo.vue
<script setup lang="ts">
import { Tabs, TabsTrigger } from "@/lib/registry/default/ui/tabs"
</script>

<template>
  <Tabs default-value="one">
    <TabsTrigger value="one">Tab one</TabsTrigger>
    <TabsTrigger value="two">Tab two</TabsTrigger>
    <TabsTrigger value="three">Tab three</TabsTrigger>
  </Tabs>
</template>
