// apps/vue/app/components/content/ComponentPreview.vue
<script setup lang="ts">
import { computed } from "vue"

import { Index } from "@/__registry__"

const props = defineProps<{ name: string }>()
const demo = computed(() => Index.default[props.name]?.component)
</script>

<template>
  <div
    class="my-6 rounded-lg border border-newt-border bg-newt-bg-elevated p-8"
  >
    <component :is="demo" v-if="demo" />
    <p v-else class="text-newt-text-muted">
      Component {{ name }} not found in registry.
    </p>
  </div>
</template>

// apps/www/components/component-preview.tsx
"use client"

import * as React from "react"

import { Index } from "@/__registry__"
import { cn } from "@/lib/utils"

interface ComponentPreviewProps extends React.HTMLAttributes<HTMLDivElement> {
  name: string
}

export function ComponentPreview({
  name,
  className,
  ...props
}: ComponentPreviewProps) {
  const entry = Index.default[name]
  const Preview = entry?.component
  return (
    <div
      className={cn(
        "my-6 rounded-lg border border-newt-border bg-newt-bg-elevated p-8",
        className
      )}
      {...props}
    >
      <React.Suspense
        fallback={<p className="text-newt-text-muted">Loading…</p>}
      >
        {Preview ? (
          <Preview />
        ) : (
          <p className="text-newt-text-muted">
            Component {name} not found in registry.
          </p>
        )}
      </React.Suspense>
    </div>
  )
}
