// apps/www/registry/bases/newt/ui/code-block.tsx
import { cva, type VariantProps } from "class-variance-authority"
import * as React from "react"

import { cn } from "@/lib/utils"

const codeTokenVariants = cva("", {
  variants: {
    kind: {
      keyword: "text-[#569cd6]",
      string: "text-[#ce9178]",
      comment: "text-[#6a9955]",
      function: "text-[#dcdcaa]",
    },
  },
})

export interface CodeTokenProps
  extends
    React.ComponentProps<"span">,
    VariantProps<typeof codeTokenVariants> {}

const CodeToken = React.forwardRef<HTMLSpanElement, CodeTokenProps>(
  ({ className, kind, ...props }, ref) => (
    <span
      ref={ref}
      className={cn(codeTokenVariants({ kind }), className)}
      {...props}
    />
  )
)
CodeToken.displayName = "CodeToken"

/** A run of text, coloured by `kind` when given, plain when not. */
export interface CodeTokenSpec {
  readonly text: string
  readonly kind?: VariantProps<typeof codeTokenVariants>["kind"]
}

export interface CodeBlockProps extends React.ComponentProps<"pre"> {
  /**
   * A flat list of runs, including the line breaks as `{ text: "\n" }`. This
   * is the syntax most callers want: a highlighter (or a hand-written token
   * list) produces one array, with no JSX whitespace to get exactly right —
   * `children` still renders as-is for anything composed by hand.
   */
  tokens?: readonly CodeTokenSpec[]
}

const CodeBlock = React.forwardRef<HTMLPreElement, CodeBlockProps>(
  ({ className, tokens, children, ...props }, ref) => (
    <pre
      ref={ref}
      className={cn(
        "overflow-x-auto rounded-md border border-newt-border bg-[#111214] p-4 font-mono text-[13px] leading-[1.6] text-newt-text-secondary",
        className
      )}
      {...props}
    >
      {tokens
        ? tokens.map((token, index) =>
            token.kind ? (
              <CodeToken key={index} kind={token.kind}>
                {token.text}
              </CodeToken>
            ) : (
              <React.Fragment key={index}>{token.text}</React.Fragment>
            )
          )
        : children}
    </pre>
  )
)
CodeBlock.displayName = "CodeBlock"

export { CodeBlock, CodeToken, codeTokenVariants }

// apps/vue/registry/bases/newt/ui/code-block/CodeBlock.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue"

import { cn } from "@/lib/utils"

import type { CodeTokenSpec } from "."
import CodeToken from "./CodeToken.vue"

/*
 * `tokens` is the syntax most callers want: a flat list of runs, including
 * the line breaks as `{ text: "\n" }`. A highlighter (or a hand-written
 * token list) produces one array, with no whitespace-sensitive template
 * markup to get exactly right — the default slot still renders as-is for
 * anything composed by hand.
 */
const props = defineProps<{
  class?: HTMLAttributes["class"]
  tokens?: readonly CodeTokenSpec[]
}>()
</script>

<template>
  <pre
    :class="
      cn(
        'overflow-x-auto rounded-md border border-newt-border bg-[#111214] p-4 font-mono text-[13px] leading-[1.6] text-newt-text-secondary',
        props.class
      )
    "
  ><template v-if="props.tokens"><template v-for="(token, index) in props.tokens" :key="index"><CodeToken v-if="token.kind" :kind="token.kind">{{ token.text }}</CodeToken><template v-else>{{ token.text }}</template></template></template><slot v-else /></pre>
</template>
