// apps/vue/app/components/docs/ComponentSection.vue
<script setup lang="ts">
import { computed } from "vue"

const props = withDefaults(
  defineProps<{
    index: number
    name: string
    title: string
    rootClass?: string
    description?: string
  }>(),
  { rootClass: undefined, description: undefined }
)

const num = computed<string>(() => String(props.index).padStart(2, "0"))
</script>

<template>
  <section :id="props.name" class="component-section">
    <div class="component-section__head">
      <div class="component-section__num">{{ num }}</div>
      <div class="component-section__title">
        {{ props.title }}
        <span v-if="props.rootClass" class="component-section__class"
          >.{{ props.rootClass }}</span
        >
      </div>
      <p v-if="props.description" class="component-section__desc">
        {{ props.description }}
      </p>
    </div>
    <div class="component-section__body">
      <slot />
    </div>
  </section>
</template>

// apps/www/components/docs/component-section.tsx
import * as React from "react"

interface ComponentSectionProps {
  id: string
  index: number
  title: string
  rootClass?: string
  description?: string
  children: React.ReactNode
}

export function ComponentSection({
  id,
  index,
  title,
  rootClass,
  description,
  children,
}: ComponentSectionProps) {
  return (
    <section className="component-section" id={id}>
      <div className="component-section__head">
        <div className="component-section__num">
          {String(index).padStart(2, "0")}
        </div>
        <div className="component-section__title">
          {title}
          {rootClass ? (
            <span className="component-section__class">{rootClass}</span>
          ) : null}
        </div>
        {description ? (
          <p className="component-section__desc">{description}</p>
        ) : null}
      </div>
      <div className="component-section__body">{children}</div>
    </section>
  )
}
