// apps/vue/app/components/docs/Preview.vue
<script setup lang="ts">
import { ref } from "vue"

const props = withDefaults(
  defineProps<{
    code?: string
    dark?: boolean
    column?: boolean
  }>(),
  { code: undefined, dark: false, column: false }
)

const contentRef = ref<HTMLDivElement | null>(null)
const { copied, copy } = useCopyToClipboard()

function formatMarkup(html: string): string {
  return html
    .split("\n")
    .map((line) => line.trim())
    .filter((line) => line.length > 0)
    .join("\n")
}

async function copySource(): Promise<void> {
  const source =
    props.code ??
    (contentRef.value ? formatMarkup(contentRef.value.innerHTML) : "")
  await copy(source)
}
</script>

<template>
  <div
    class="preview"
    :class="{ 'preview--dark': props.dark, 'preview--col': props.column }"
  >
    <button
      class="preview__copy"
      :class="{ 'is-copied': copied }"
      type="button"
      @click="copySource"
    >
      {{ copied ? "Copied" : "Copy" }}
    </button>
    <div ref="contentRef" class="preview__content">
      <slot />
    </div>
  </div>
</template>

// apps/www/components/docs/preview.tsx
"use client"

import * as React from "react"

interface PreviewProps {
  children: React.ReactNode
  /** Markup or code copied by the copy button. */
  code?: string
  /** Renders on the deepest background, like the original `.preview--dark`. */
  dark?: boolean
  /** Stacks the preview content vertically (`.preview--col`). */
  column?: boolean
  className?: string
}

export function Preview({
  children,
  code,
  dark,
  column,
  className,
}: PreviewProps) {
  const [copied, setCopied] = React.useState(false)
  const contentRef = React.useRef<HTMLDivElement>(null)

  const copy = async () => {
    const markup =
      code ??
      (contentRef.current?.innerHTML ?? "")
        .split("\n")
        .map((line) => line.trim())
        .filter(Boolean)
        .join("\n")
    try {
      await navigator.clipboard.writeText(markup)
      setCopied(true)
      setTimeout(() => setCopied(false), 1500)
    } catch {
      // clipboard unavailable — ignore, same as the original docs
    }
  }

  return (
    <div
      className={[
        "preview",
        dark ? "preview--dark" : "",
        column ? "preview--col" : "",
        className ?? "",
      ]
        .filter(Boolean)
        .join(" ")}
    >
      <button
        className={`preview__copy${copied ? " is-copied" : ""}`}
        onClick={() => void copy()}
        type="button"
      >
        {copied ? "Copied" : "Copy"}
      </button>
      <div className="preview__content" ref={contentRef}>
        {children}
      </div>
    </div>
  )
}
