// apps/vue/app/lib/registry/default/ui/divider/Divider.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue"

import { cn } from "@/lib/utils"

const props = defineProps<{ class?: HTMLAttributes["class"] }>()
</script>

<template>
  <div
    role="separator"
    :class="
      cn(
        'my-4 flex items-center gap-3 text-xs font-semibold text-newt-text-muted',
        'before:h-px before:flex-1 before:bg-newt-border before:content-[\'\']',
        'after:h-px after:flex-1 after:bg-newt-border after:content-[\'\']',
        props.class
      )
    "
  >
    <slot />
  </div>
</template>

// apps/www/registry/default/ui/divider.tsx
import * as React from "react"

import { cn } from "@/lib/utils"

const Divider = React.forwardRef<
  HTMLDivElement,
  React.HTMLAttributes<HTMLDivElement>
>(({ className, children, ...props }, ref) => (
  <div
    ref={ref}
    role="separator"
    className={cn(
      "my-4 flex items-center gap-3 text-xs font-semibold text-newt-text-muted",
      "before:h-px before:flex-1 before:bg-newt-border before:content-['']",
      "after:h-px after:flex-1 after:bg-newt-border after:content-['']",
      className
    )}
    {...props}
  >
    {children}
  </div>
))
Divider.displayName = "Divider"

export { Divider }
