// apps/vue/app/lib/registry/default/example/AttachmentDemo.vue
<script setup lang="ts">
import {
  Attachment,
  AttachmentIcon,
  AttachmentMeta,
  AttachmentName,
  AttachmentSize,
} from "@/lib/registry/default/ui/attachment"
import { Button } from "@/lib/registry/default/ui/button"
</script>

<template>
  <Attachment>
    <AttachmentIcon>FILE</AttachmentIcon>
    <AttachmentMeta>
      <AttachmentName>filename.ext</AttachmentName>
      <AttachmentSize>1.2 MB</AttachmentSize>
    </AttachmentMeta>
    <Button variant="icon" aria-label="Download file">⬇</Button>
  </Attachment>
</template>

// apps/www/registry/default/example/attachment-demo.tsx
import {
  Attachment,
  AttachmentIcon,
  AttachmentMeta,
  AttachmentName,
  AttachmentSize,
} from "@/registry/default/ui/attachment"
import { Button } from "@/registry/default/ui/button"

export default function AttachmentDemo() {
  return (
    <Attachment>
      <AttachmentIcon>FILE</AttachmentIcon>
      <AttachmentMeta>
        <AttachmentName>filename.ext</AttachmentName>
        <AttachmentSize>1.2 MB</AttachmentSize>
      </AttachmentMeta>
      <Button variant="icon" aria-label="Download file">
        ⬇
      </Button>
    </Attachment>
  )
}
