// apps/vue/app/lib/registry/default/example/ChannelTopicDemo.vue
<script setup lang="ts">
import {
  ChannelTopic,
  ChannelTopicDescription,
  ChannelTopicDivider,
  ChannelTopicIcon,
  ChannelTopicName,
} from "@/lib/registry/default/ui/channel-topic"
</script>

<template>
  <ChannelTopic class="w-full max-w-md">
    <ChannelTopicIcon />
    <ChannelTopicName>channel-name</ChannelTopicName>
    <ChannelTopicDivider />
    <ChannelTopicDescription
      >Channel topic description goes here</ChannelTopicDescription
    >
  </ChannelTopic>
</template>

// apps/www/registry/default/example/channel-topic-demo.tsx
import {
  ChannelTopic,
  ChannelTopicDescription,
  ChannelTopicDivider,
  ChannelTopicIcon,
  ChannelTopicName,
} from "@/registry/default/ui/channel-topic"

export default function ChannelTopicDemo() {
  return (
    <ChannelTopic className="w-full max-w-md">
      <ChannelTopicIcon />
      <ChannelTopicName>channel-name</ChannelTopicName>
      <ChannelTopicDivider />
      <ChannelTopicDescription>
        Channel topic description goes here
      </ChannelTopicDescription>
    </ChannelTopic>
  )
}
