// apps/vue/app/lib/registry/default/example/CodeBlockDemo.vue
<script setup lang="ts">
import { CodeBlock, CodeToken } from "@/lib/registry/default/ui/code-block"
</script>

<template>
  <CodeBlock
    ><CodeToken kind="comment">// example</CodeToken>
    <CodeToken kind="keyword">const</CodeToken>
    <CodeToken kind="function">greet</CodeToken> = () =>
    <CodeToken kind="string">"hello"</CodeToken>;</CodeBlock
  >
</template>

// apps/www/registry/default/example/code-block-demo.tsx
import { CodeBlock, CodeToken } from "@/registry/default/ui/code-block"

export default function CodeBlockDemo() {
  return (
    <CodeBlock>
      <CodeToken kind="comment">{"// example"}</CodeToken>
      {"\n"}
      <CodeToken kind="keyword">const</CodeToken>{" "}
      <CodeToken kind="function">greet</CodeToken>
      {" = () => "}
      <CodeToken kind="string">&quot;hello&quot;</CodeToken>;
    </CodeBlock>
  )
}
