// apps/vue/app/lib/registry/default/example/DropdownDemo.vue
<script setup lang="ts">
import {
  Dropdown,
  DropdownContent,
  DropdownDescription,
  DropdownDivider,
  DropdownIcon,
  DropdownItem,
  DropdownLabel,
} from "@/lib/registry/default/ui/dropdown"
</script>

<template>
  <Dropdown>
    <DropdownItem active>
      <DropdownIcon>&#x26A1;</DropdownIcon>
      <DropdownContent>
        <DropdownLabel>Option label</DropdownLabel>
        <DropdownDescription>Option description</DropdownDescription>
      </DropdownContent>
    </DropdownItem>
    <DropdownDivider />
    <DropdownItem>
      <DropdownIcon>&#x2699;</DropdownIcon>
      <DropdownContent>
        <DropdownLabel>Another option</DropdownLabel>
        <DropdownDescription>Description</DropdownDescription>
      </DropdownContent>
    </DropdownItem>
  </Dropdown>
</template>

// apps/www/registry/default/example/dropdown-demo.tsx
import {
  Dropdown,
  DropdownContent,
  DropdownDescription,
  DropdownDivider,
  DropdownIcon,
  DropdownItem,
  DropdownLabel,
} from "@/registry/default/ui/dropdown"

export default function DropdownDemo() {
  return (
    <Dropdown>
      <DropdownItem active>
        <DropdownIcon>{"⚡"}</DropdownIcon>
        <DropdownContent>
          <DropdownLabel>Option label</DropdownLabel>
          <DropdownDescription>Option description</DropdownDescription>
        </DropdownContent>
      </DropdownItem>
      <DropdownDivider />
      <DropdownItem>
        <DropdownIcon>{"⚙"}</DropdownIcon>
        <DropdownContent>
          <DropdownLabel>Another option</DropdownLabel>
          <DropdownDescription>Description</DropdownDescription>
        </DropdownContent>
      </DropdownItem>
    </Dropdown>
  )
}
