// apps/vue/app/lib/registry/default/example/ModalDemo.vue
<script setup lang="ts">
import { ref } from "vue"

import { Button } from "@/lib/registry/default/ui/button"
import {
  Modal,
  ModalBody,
  ModalClose,
  ModalFooter,
  ModalHeader,
} from "@/lib/registry/default/ui/modal"

const open = ref(false)
</script>

<template>
  <Button variant="primary" @click="open = true">Open modal</Button>
  <Modal v-model:open="open">
    <ModalHeader>Modal title</ModalHeader>
    <ModalBody>Modal body content goes here.</ModalBody>
    <ModalFooter>
      <ModalClose>
        <Button variant="secondary">Cancel</Button>
      </ModalClose>
      <Button variant="danger" @click="open = false">Confirm</Button>
    </ModalFooter>
  </Modal>
</template>

// apps/www/registry/default/example/modal-demo.tsx
"use client"

import * as React from "react"

import { Button } from "@/registry/default/ui/button"
import {
  Modal,
  ModalBody,
  ModalClose,
  ModalFooter,
  ModalHeader,
} from "@/registry/default/ui/modal"

export default function ModalDemo() {
  const [open, setOpen] = React.useState(false)

  return (
    <>
      <Button variant="primary" onClick={() => setOpen(true)}>
        Open modal
      </Button>
      <Modal open={open} onOpenChange={setOpen}>
        <ModalHeader>Modal title</ModalHeader>
        <ModalBody>Modal body content goes here.</ModalBody>
        <ModalFooter>
          <ModalClose asChild>
            <Button variant="secondary">Cancel</Button>
          </ModalClose>
          <Button variant="danger" onClick={() => setOpen(false)}>
            Confirm
          </Button>
        </ModalFooter>
      </Modal>
    </>
  )
}
