// apps/vue/app/lib/registry/default/example/SkeletonDemo.vue
<script setup lang="ts">
import { Skeleton } from "@/lib/registry/default/ui/skeleton"
</script>

<template>
  <div class="flex w-full max-w-sm gap-3">
    <Skeleton variant="avatar" />
    <div class="flex flex-1 flex-col gap-1.5">
      <Skeleton variant="title" />
      <Skeleton variant="text" class="w-[80%]" />
    </div>
  </div>
</template>

// apps/www/registry/default/example/skeleton-demo.tsx
import { Skeleton } from "@/registry/default/ui/skeleton"

export default function SkeletonDemo() {
  return (
    <div className="flex w-full max-w-sm gap-3">
      <Skeleton variant="avatar" />
      <div className="flex flex-1 flex-col gap-1.5">
        <Skeleton variant="title" />
        <Skeleton variant="text" className="w-[80%]" />
      </div>
    </div>
  )
}
