// apps/vue/app/lib/registry/default/example/TimelineDemo.vue
<script setup lang="ts">
import {
  Timeline,
  TimelineContent,
  TimelineDot,
  TimelineItem,
  TimelineMeta,
  TimelineTitle,
} from "@/lib/registry/default/ui/timeline"
</script>

<template>
  <Timeline class="w-full max-w-sm">
    <TimelineItem>
      <TimelineDot variant="brand">↻</TimelineDot>
      <TimelineContent>
        <TimelineTitle>Event title</TimelineTitle>
        <TimelineMeta>Detail · timestamp</TimelineMeta>
      </TimelineContent>
    </TimelineItem>
    <TimelineItem>
      <TimelineDot variant="success">✓</TimelineDot>
      <TimelineContent>
        <TimelineTitle>Event title</TimelineTitle>
        <TimelineMeta>Detail · timestamp</TimelineMeta>
      </TimelineContent>
    </TimelineItem>
  </Timeline>
</template>

// apps/www/registry/default/example/timeline-demo.tsx
import {
  Timeline,
  TimelineContent,
  TimelineDot,
  TimelineItem,
  TimelineMeta,
  TimelineTitle,
} from "@/registry/default/ui/timeline"

export default function TimelineDemo() {
  return (
    <Timeline className="w-full max-w-sm">
      <TimelineItem>
        <TimelineDot variant="brand">↻</TimelineDot>
        <TimelineContent>
          <TimelineTitle>Event title</TimelineTitle>
          <TimelineMeta>Detail · timestamp</TimelineMeta>
        </TimelineContent>
      </TimelineItem>
      <TimelineItem>
        <TimelineDot variant="success">✓</TimelineDot>
        <TimelineContent>
          <TimelineTitle>Event title</TimelineTitle>
          <TimelineMeta>Detail · timestamp</TimelineMeta>
        </TimelineContent>
      </TimelineItem>
    </Timeline>
  )
}
