// apps/vue/app/lib/registry/default/example/VoiceChannelDemo.vue
<script setup lang="ts">
import { Avatar } from "@/lib/registry/default/ui/avatar"
import {
  VoiceChannel,
  VoiceChannelHeader,
  VoiceChannelIcon,
  VoiceChannelMember,
  VoiceChannelMemberIcons,
  VoiceChannelMembers,
} from "@/lib/registry/default/ui/voice-channel"
</script>

<template>
  <VoiceChannel class="w-60">
    <VoiceChannelHeader>
      <VoiceChannelIcon>🔊</VoiceChannelIcon>
      Channel name
    </VoiceChannelHeader>
    <VoiceChannelMembers>
      <VoiceChannelMember>
        <Avatar size="sm">A</Avatar>
        username
        <VoiceChannelMemberIcons>🎙️</VoiceChannelMemberIcons>
      </VoiceChannelMember>
    </VoiceChannelMembers>
  </VoiceChannel>
</template>

// apps/www/registry/default/example/voice-channel-demo.tsx
import { Avatar } from "@/registry/default/ui/avatar"
import {
  VoiceChannel,
  VoiceChannelHeader,
  VoiceChannelIcon,
  VoiceChannelMember,
  VoiceChannelMemberIcons,
  VoiceChannelMembers,
} from "@/registry/default/ui/voice-channel"

export default function VoiceChannelDemo() {
  return (
    <VoiceChannel className="w-60">
      <VoiceChannelHeader>
        <VoiceChannelIcon>🔊</VoiceChannelIcon>
        Channel name
      </VoiceChannelHeader>
      <VoiceChannelMembers>
        <VoiceChannelMember>
          <Avatar size="sm">A</Avatar>
          username
          <VoiceChannelMemberIcons>🎙️</VoiceChannelMemberIcons>
        </VoiceChannelMember>
      </VoiceChannelMembers>
    </VoiceChannel>
  )
}
