// apps/vue/app/pages/docs/components/[name].vue
<script setup lang="ts">
import type { Component } from "vue"
import { computed } from "vue"

import { Index } from "@/__registry__"
import ComponentSection from "@/components/docs/ComponentSection.vue"
import Preview from "@/components/docs/Preview.vue"
import { categories } from "@/lib/registry/registry-categories"
import { rootClasses } from "@/lib/registry/registry-root-classes"
import { ui } from "@/lib/registry/registry-ui"

/** Number of hand-written sections on the home page (`installation`, `tokens`). */
const STATIC_SECTIONS = 2

const order: string[] = categories.flatMap((category) => category.components)

function pascalCase(name: string): string {
  return name
    .split("-")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("")
}

const route = useRoute()
const name = computed<string>(() => String(route.params.name))
const item = computed(() =>
  ui.find((registryItem) => registryItem.name === name.value)
)
const index = computed<number>(
  () => order.indexOf(name.value) + 1 + STATIC_SECTIONS
)
const demo = computed<Component | undefined>(() => {
  const entry = Index.default[`${pascalCase(name.value)}Demo`]
  return entry?.component
})

useHead(() => ({ title: `${item.value?.title ?? name.value} — newt/ui` }))
</script>

<template>
  <div class="content">
    <ComponentSection
      v-if="item"
      :index="index"
      :name="item.name"
      :title="item.title ?? item.name"
      :root-class="rootClasses[item.name]"
      :description="item.description"
    >
      <Preview>
        <component :is="demo" v-if="demo" />
        <p v-else class="component-section__desc">No demo available.</p>
      </Preview>
    </ComponentSection>
    <ComponentSection
      v-else
      :index="0"
      name="not-found"
      title="Component not found"
      :description="`No registry entry matches “${name}”.`"
    >
      <Preview>
        <p class="component-section__desc">
          Check the sidebar for the full component list.
        </p>
      </Preview>
    </ComponentSection>
  </div>
</template>

// apps/www/app/docs/components/[name]/page.tsx
import { notFound } from "next/navigation"

import { Demos } from "@/__registry__/demos"
import { ComponentSection } from "@/components/docs/component-section"
import { Preview } from "@/components/docs/preview"
import { categories } from "@/registry/registry-categories"
import { rootClasses } from "@/registry/registry-root-classes"
import { ui } from "@/registry/registry-ui"

export function generateStaticParams() {
  return ui.map((item) => ({ name: item.name }))
}

export default async function ComponentPage({
  params,
}: {
  params: Promise<{ name: string }>
}) {
  const { name } = await params
  const item = ui.find((entry) => entry.name === name)
  if (!item) notFound()

  const category = categories.find((entry) => entry.components.includes(name))
  const index = category ? category.components.indexOf(name) + 1 : 1
  const Demo = Demos[name]

  return (
    <>
      <header className="page-header">
        <div className="page-header__main">
          <div className="page-header__eyebrow">
            <span>newt/ui</span>
            <span>·</span>
            <span>
              <b>{category?.label ?? "Components"}</b>
            </span>
          </div>
          <h1>
            <em>component —</em>
            {item.title ?? item.name}
          </h1>
          {item.description ? <p className="lead">{item.description}</p> : null}
        </div>
        <div className="page-header__manifest">
          <div className="manifest__heading">registry-item</div>
          <div className="manifest__row">
            <span className="manifest__key">name</span>
            <span className="manifest__val manifest__val--brand">
              {item.name}
            </span>
          </div>
          <div className="manifest__row">
            <span className="manifest__key">root class</span>
            <span className="manifest__val">{rootClasses[name] ?? "—"}</span>
          </div>
          <div className="manifest__row">
            <span className="manifest__key">depends on</span>
            <span className="manifest__val">
              {item.registryDependencies?.join(", ") ?? "none"}
            </span>
          </div>
          <div className="manifest__row">
            <span className="manifest__key">install</span>
            <span className="manifest__val">newt-ui add {item.name}</span>
          </div>
        </div>
      </header>

      <div className="content">
        <ComponentSection
          id={name}
          index={index}
          title={item.title ?? item.name}
          rootClass={rootClasses[name]}
          description={item.description}
        >
          <Preview>{Demo ? <Demo /> : null}</Preview>
        </ComponentSection>
      </div>
    </>
  )
}
